### ISSUE TITLE
No such module 'collection_view_layouts'

### ISSUE THREAD

**Issue by bogdanh** [rubygarage/collection-view-layouts#12]
I've followed the How-to for the Example project but when I'm trying to build it I am getting "No such module 'collection_view_layouts' in ViewControllers/ViewController.swift.

What am I doing wrong? Or is something missing?

Regards.

**Comment by plzen** [comment]
There are 2 ways how to run the example. First:
1. Clone repository
2. Open Example folder and run `pod install` command to fetch all dependencies
3. Open `collection-view-layouts.xcworkspace` and run project

Second:
You can use `pod try collection-view-layouts` and run project after opening XCode.

**Comment by bogdanh** [comment]
Thank you for the reply, @plzen. Finally, was able to build and run it.

Best regards.
