### ISSUE TITLE
Horizontal scrolling support

### ISSUE THREAD

**Issue by fr-josh** [rubygarage/collection-view-layouts#16]
I have been trying to set the TagsStyleFlowLayout to work with a horizontally scrolling UICollectionView but it seems the layout overrides this and forces it to scroll vertically.

It would be very useful to allow it scroll horizontally as well.

**Comment by shuuja** [comment]
Do we have horizontal scrolling for instagram flow layout?

**Comment by radyslavkrechet** [comment]
Hello @fr-josh! We've added horizontal scroll for tags layout. Update the pod to the latest version 0.2.2 and enjoy.
Hi @shuuja. We decided to not implement horizontal scroll for other layouts because there is the implementation of social networks layouts that have vertical scroll only.
