### ISSUE TITLE
Usage with images from the web

### ISSUE THREAD

**Issue by n1schal** [rubygarage/collection-view-layouts#18]
Hi

Just stumbled upon this library while looking to arrange items in different layouts.

How do I use this with images loaded from the web? As far as I've seen, the sample app returns cell size according to the length of the string placed in the corresponding item. I'd be very thankful if you could guide me as to how I could implement one of these layouts with URL of the image link.

**Comment by radyslavkrechet** [comment]
@n1schal, hi!

We have two types of layouts:
- with a fixed size, size of cells depends on screen size (Flickr, Facebook, Flipboard, Instagram); with these layouts, you shouldn't implement `ContentDynamicLayoutDelegate`; in this case, you can use `UIImageView` with `Aspect Fill` content mode;
- with dynamic size (Pinterest with fixed width but dynamic height, px500 with fixed height but dynamic width, tags with dynamic height and width); with these layouts, you should implement `ContentDynamicLayoutDelegate` and return value of the dynamic side; these layouts could be used only if you have some metadata about images' size (proportion or exact size) before images will load.
