### ISSUE TITLE
Baselayout not found

### ISSUE THREAD

**Issue by tuppaware** [rubygarage/collection-view-layouts#22]
Seems your example is different from the current pod?

**Comment by plzen** [comment]
Hi @tuppaware,
I've just pushed last release and updated pod trunk to the latest version.
Try to update the library to 0.2.2.

**Comment by jerrychong25** [comment]
> Hi @tuppaware,
> I've just pushed last release and updated pod trunk to the latest version.
> Try to update the library to 0.2.2.

Thanks!

`pod 'collection-view-layouts/Core', '~> 0.2.2'` do the trick and fixed this error.
