### ISSUE TITLE
3 x 3 Layout Type?

### ISSUE THREAD

**Issue by jerrychong25** [rubygarage/collection-view-layouts#23]
Hi all,

Thanks for providing great layouts on 7 layout types (Tags, Pinterest, 500px, Instagram, Flipboard, Facebook, Flickr).

However, I would like to have a 3 x 3 layout which is similar to **Flipboard Layout** on second, third and fifth row, as per screenshot below:
<img width="334" alt="Screenshot 2019-07-30 at 1 42 43 PM" src="https://user-images.githubusercontent.com/15714095/62104061-04cd8e80-b2d1-11e9-965a-8bab10dc7a5f.png">

What should I set to achieve this layout?

Thanks.

**Comment by radyslavkrechet** [comment]
Hello, @jerrychong25!

As I understand, you need the typical grid, so you can use Instagram layout with default grid mode. If I understood you incorrect, fill free and let me know more details about your demand.

**Comment by jerrychong25** [comment]
> Hello, @jerrychong25!
> 
> As I understand, you need the typical grid, so you can use Instagram layout with default grid mode. If I understood you incorrect, fill free and let me know more details about your demand.

@radyslavkrechet 

Thanks, it is working!

Code:
```
layout = InstagramLayout()
layout.gridType = .defaultGrid
```

Screenshot:
![Screenshot 2019-07-30 at 2 33 00 PM](https://user-images.githubusercontent.com/15714095/62106115-f1bdbd00-b2d6-11e9-99aa-6a2b37957bc5.png)

**Comment by jerrychong25** [comment]
@radyslavkrechet 

I found one small issue on using this Instagram Layout.

If my displaying text (Example: Too Long Already) is too long, it will omitted automatically, as per screenshot below:
![Screenshot 2019-07-30 at 2 52 30 PM](https://user-images.githubusercontent.com/15714095/62107749-dbb1fb80-b2da-11e9-91cc-ccb7669ea6d7.png)

How could I set to display this long text in two row?

Thanks.

**Comment by radyslavkrechet** [comment]
Just use `numberOfLines` property of label with value 0 for not restricted number of lines or with some specific value (for example, 2):
https://stackoverflow.com/questions/990221/multiple-lines-of-text-in-uilabel
You can also change this parameter from Xcode Interface Builder. And you can use any custom collection view cell with these layouts.

**Comment by jerrychong25** [comment]
> Just use `numberOfLines` property of label with value 0 for not restricted number of lines or with some specific value (for example, 2):
> https://stackoverflow.com/questions/990221/multiple-lines-of-text-in-uilabel
> You can also change this parameter from Xcode Interface Builder. And you can use any custom collection view cell with these layouts.

Thanks, it is working!

Screenshot:
![Screenshot 2019-07-30 at 4 38 11 PM](https://user-images.githubusercontent.com/15714095/62114085-76fd9d80-b2e8-11e9-8cd6-ec7756cc9baf.png)

**Comment by jerrychong25** [comment]
> Just use `numberOfLines` property of label with value 0 for not restricted number of lines or with some specific value (for example, 2):
> https://stackoverflow.com/questions/990221/multiple-lines-of-text-in-uilabel
> You can also change this parameter from Xcode Interface Builder. And you can use any custom collection view cell with these layouts.

@radyslavkrechet 

I tried to add **UICollectionViewDelegate** in **ContentViewProvider.swift** for detecting user clicked contentCell as per https://stackoverflow.com/questions/46987928/swift-click-onto-cell-of-uicollectionview-and-open-alertviewcontroller, but it is not working.

Is there any way to get clickable **indexPath** fo **contentCell** when user pressed on it?

Thanks.

**Comment by radyslavkrechet** [comment]
I think you didn't set delegate of the collection view. Just add `collectionView.delegate = collectionViewProvider` in the `setupCollectionView` function of the `ViewController`.

**Comment by jerrychong25** [comment]
Tried adding `collectionView.delegate = collectionViewProvider` into the code, but still not working.

My code as per below:

**setupCollectionView() in ViewController.swift:**
```
    private func setupCollectionView() {
        collectionView.dataSource = collectionViewProvider

        let firstSectionItems = [“Test1”, "Test2”, "Test3”, "Test4”, "Test5”, "Test6”, "Test7”, "Test8”, "Test9”]

        collectionViewProvider.items = [firstSectionItems]
        collectionViewProvider.supplementaryItems = [“Title”]
        
        collectionView.delegate = collectionViewProvider
    }
```

**CollectionViewProvider.swift:**
```
import UIKit

class CollectionViewProvider: NSObject, UICollectionViewDataSource, UICollectionViewDelegate {
    var items = [[String]]()
    var supplementaryItems = [String]()

    @IBOutlet var collectionView: UICollectionView!
    
    // MARK: - UICollectionViewDataSource

    func numberOfSections(in collectionView: UICollectionView) -> Int {
        NSLog("ViewController numberOfSections()")
        
        return supplementaryItems.count
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        NSLog("ViewController collectionView() 1 \(section)")
        
        return items[section].count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        NSLog("ViewController collectionView() 2 \(indexPath)")
        
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "ContentCellIdentifier", for: indexPath)

        cell.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(tap(_:))))
        
        if let cell = cell as? ContentCell {
            let item = items[indexPath.section][indexPath.row]
            cell.populate(with: item)
        }
        
        return cell
    }
    
    @IBAction func tap(_ sender: UITapGestureRecognizer) {

        let location = sender.location(in: self.collectionView)
        let indexPath = self.collectionView.indexPathForItem(at: location)

        if let index = indexPath {
            print("Got clicked on index: \(index)!")
        }
    }

    func collectionView(_ collectionView: UICollectionView,
                        viewForSupplementaryElementOfKind kind: String,
                        at indexPath: IndexPath) -> UICollectionReusableView {
        
        NSLog("ViewController collectionView() 3 \(indexPath)")

        if kind == UICollectionView.elementKindSectionHeader {
            let headerView = collectionView.dequeueReusableSupplementaryView(ofKind: kind,
                                                                             withReuseIdentifier: "HeaderViewIdentifier",
                                                                             for: indexPath)

            if let headerView = headerView as? HeaderView {
                let item = supplementaryItems[indexPath.section]
                headerView.populate(with: item)
            }

            return headerView
        } else {
            let footerView = collectionView.dequeueReusableSupplementaryView(ofKind: kind,
                                                                             withReuseIdentifier: "FooterViewIdentifier",
                                                                             for: indexPath)

            if let footerView = footerView as? FooterView {
                let item = supplementaryItems[indexPath.section]
                footerView.populate(with: item)
            }

            return footerView
        }
    }
}
```

**Comment by jerrychong25** [comment]
Fixed this issue.

The previous Stackoverflow answer does not work in my case, however this one (https://stackoverflow.com/questions/31735228/how-to-make-a-simple-collection-view-with-swift) is working:
```
import UIKit

class CollectionViewProvider: NSObject, UICollectionViewDataSource, UICollectionViewDelegate {
    var items = [[String]]()
    var supplementaryItems = [String]()
    
    // MARK: - UICollectionViewDataSource

    func numberOfSections(in collectionView: UICollectionView) -> Int {
        NSLog("ViewController numberOfSections()")
        
        return supplementaryItems.count
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        NSLog("ViewController collectionView() 1 \(section)")
        
        return items[section].count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        NSLog("ViewController collectionView() 2 \(indexPath)")
        
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "ContentCellIdentifier", for: indexPath)
        
        if let cell = cell as? ContentCell {
            let item = items[indexPath.section][indexPath.row]
            cell.populate(with: item)
        }
        
        return cell
    }

    func collectionView(_ collectionView: UICollectionView,
                        viewForSupplementaryElementOfKind kind: String,
                        at indexPath: IndexPath) -> UICollectionReusableView {
        
        NSLog("ViewController collectionView() 3 \(indexPath)")

        if kind == UICollectionView.elementKindSectionHeader {
            let headerView = collectionView.dequeueReusableSupplementaryView(ofKind: kind,
                                                                             withReuseIdentifier: "HeaderViewIdentifier",
                                                                             for: indexPath)

            if let headerView = headerView as? HeaderView {
                let item = supplementaryItems[indexPath.section]
                headerView.populate(with: item)
            }

            return headerView
        } else {
            let footerView = collectionView.dequeueReusableSupplementaryView(ofKind: kind,
                                                                             withReuseIdentifier: "FooterViewIdentifier",
                                                                             for: indexPath)

            if let footerView = footerView as? FooterView {
                let item = supplementaryItems[indexPath.section]
                footerView.populate(with: item)
            }

            return footerView
        }
    }
    
    // MARK: - UICollectionViewDelegate protocol
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        // handle tap events
        NSLog("ViewController collectionView() 4 \(indexPath.item)")
    }
}

```
