### ISSUE TITLE
Got an warning  "[!] Unable to read the license file `LICENSE` for the spec `collection-view-layouts (0.1.2)`"

### ISSUE THREAD

**Issue by tony-hoang999** [rubygarage/collection-view-layouts#32]
Hello,

Thank you for the library. It works well on my project. 

However, there is a minor error when running `pod install`. The warning is "[!] Unable to read the license file `LICENSE` for the spec `collection-view-layouts (0.1.2)`". As a result, it fails to achieve the license information in LICENSE file which is needed in my project.
I think the cause of the warning is the name of the license file, it should be `LICENSE` (without .txt). Otherwise, Cocoapods won't be able to read the file.

Thank you again.
Tony Hoang

**Comment by plzen** [comment]
Hello @tony-hoang999, this bug was fixed in version 0.2.2. 
Please, try to update and feel free to reopen this issue if you get this warning.

**Comment by tony-hoang999** [comment]
Awesome. Thank you so much @plzen !
